server.port: 8080

# swagger enable
springfox.documentation.swagger.v2.enabled: true

# Log4j2
logging:
  file:
    path: logs
  level: ## LOGGING LEVEL : 1) ERROR 2) WARN 3) INFO 4) DEBUG 5) TRACE
    root: info

spring:
#  config.active.on-profile: local
  mvc:
    pathmatch:
#      강제로 WebMvcRequestHandlerProvider를 소스안에 복사한것을 적용시키기 위한 항목
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: dboo.studio@gmail.com
    password: eoghks1@!2_
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:25432/dboostudio
    username: dboostudio
    password: eoghks1@!2_
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# cors 설정
cors:
  allowed-origins: http://localhost:${server.port}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:${server.port}/oauth/redirect