version: '3.9'

services:
  databases:
    image: postgres
    restart: always
    container_name: api
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: dboostudio
      POSTGRES_PASSWORD: eoghks1@!2_
      TZ: Asia/Seoul
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data